### ISSUE TITLE
Does not work with django-filters 2.0.0

### ISSUE THREAD

**Issue by efagerberg** [philipn/django-rest-framework-filters#268]
Python 3.6
django-filter 2.0
Django 2.0.8
djangorestframework 3.8.2
djangorestframework-filters 0.10.2

```  File "api/viewsets.py", line 4, in <module>
    from api.filters import (
  File "api/filters.py", line 10, in <module>
    class GarageFilter(filters.FilterSet):
  File "/usr/local/lib/python3.6/site-packages/rest_framework_filters/filterset.py", line 44, in __new__
    opts.fields = {f.name: f.lookups or []}
AttributeError: 'RelatedFilter' object has no attribute 'name'

class GarageFilter(filters.FilterSet):
    cars = filters.RelatedFilter('api.filters.CarsFilter',
                                     queryset=Cars.objects.all(),
                                     distinct=True)
```

**Comment by efagerberg** [comment]
@rpkilby let me know if you need any more information

**Comment by rpkilby** [comment]
Hi @efagerberg. The 1.0 milestone is nearly ready for release, which has compatibility with the latest versions of Django and django-filter. 

At this point, I'm just working on docs, so it should be relatively safe to install from my master, until 1..0 is released.

**Comment by efagerberg** [comment]
Thanks for the info good to know it is on it's way
